import React, { createContext, useContext, useMemo, useState } from "react"

const LanguageContext = createContext(null)

const languageOrder = ["en", "ta", "si"]

const translations = {
  en: {
    language: "EN",
    common: {
      back: "Back",
      or: "or",
      guest: "Guest",
      novice: "Novice",
      cancel: "Cancel",
    },
    landing: {
      welcomeTo: "Welcome to",
      brainAdventure: "Brain Adventure",
      comeJoin: "Come join the adventure",
      start: "Start",
    },
    dashboard: {
      soundOn: "Turn sound on",
      soundOff: "Turn sound off",
      startQuiz: "Start Quiz",
    },
    intro: {
      browserNoVideo: "Your browser does not support the video tag.",
      playNow: "Play Now",
      soundOn: "Turn sound on",
      soundOff: "Turn sound off",
    },
    login: {
      player: "Player",
      login: "Login",
      welcomeBack: "Welcome back, explorer",
      usernameOrEmail: "USERNAME OR EMAIL",
      password: "PASSWORD",
      authenticating: "AUTHENTICATING...",
      startAdventure: "Start Adventure",
      verifyingGoogle: "Verifying Google account...",
      welcome: "Welcome",
      newExplorer: "New Explorer? Join Now!",
      forgotPassword: "Forgot Password?",
    },
    register: {
      joinThe: "Join the",
      circle: "Circle",
      createAccount: "Create your account",
      firstName: "FIRST NAME",
      lastName: "LAST NAME",
      nickname: "CHOOSE NICKNAME",
      emailAddress: "EMAIL ADDRESS",
      secretPassword: "SECRET PASSWORD",
      joining: "JOINING...",
      joinTribe: "Join Tribe",
      verifyingGoogle: "Verifying Google account...",
      alreadyMember: "Already a member? Log in here",
    },
    leaderboard: {
      title: "Leaderboard",
      loadingChampions: "Loading Champions...",
      loadError: "Could not load leaderboard. Please try again.",
      you: "YOU",
      totalMarks: "Total Marks",
      noPlayers: "No players found yet. Be the first!",
      level: "Level",
    },
    account: {
      backToMap: "Back to Map",
      editProfile: "Edit Profile",
      changeImage: "Change Image",
      touchUpload: "Touch image to upload (Max 1MB)",
      remove: "Remove",
      nickname: "Nickname (Username)",
      chooseCoolName: "CHOOSE A COOL NAME",
      firstName: "First Name",
      lastName: "Last Name",
      saveProfile: "Save Profile",
      saving: "Saving...",
      security: "Security",
      currentPassword: "Current Password",
      newPassword: "New Password",
      confirmPassword: "Confirm Password",
      updatePassword: "Update Password",
      changing: "Changing...",
      fullName: "Full Name",
      emailAddress: "Email Address",
      currentLevel: "Current Level",
      totalScore: "Total Score",
      points: "Points",
      levelHistory: "Level History",
      level: "Level",
      time: "Time",
      stars: "Stars",
      status: "Status",
      perfect: "Perfect",
      done: "Done",
      tried: "Tried",
      password: "Password",
      logoutAccount: "Logout Account",
      profileUpdated: "Profile updated!",
      passwordChanged: "Password changed!",
      passwordsNoMatch: "Passwords do not match",
      imageTooLarge: "Image is too large! Please choose a smaller one (Max 1MB).",
      updateFailed: "Update failed",
      changeFailed: "Change failed",
      notSet: "SET",
      na: "N/A",
    },
    result: {
      youWon: "You Won",
      level: "Level",
      yourReward: "Your Reward",
      marksRawScore: "Marks",
      rawScore: "Raw Score",
      openGift: "Open Gift",
      next: "Next",
      home: "Home",
      jackpot: "Jackpot!",
      diamondsFound: "DIAMONDS FOUND",
      collectAll: "Collect All",
      sound: "Sound",
      music: "Music",
      help: "Help",
      replay: "Replay",
      helpMessage: "Solve Banana Puzzles to earn Diamonds! Complete all 3 puzzles in a level to unlock the next one.",
    },
    otp: {
      enterOtp: "Enter 6-digit OTP",
      resendIn: "Resend in",
      resendOtp: "Resend OTP",
      failedResend: "Failed to resend",
      invalidCode: "Invalid code",
      devCode: "Dev code",
      verify: "Verify",
    },
    game: {
      brainAdventure: "Brain Adventure",
      levelUp: "Level Up",
      mathTerminal: "Math Terminal",
      mechanicsShiftUnlocked: "Mechanics Shift Unlocked",
      level: "Level",
      score: "Score",
      attempts: "Attempts",
      puzzle: "Puzzle",
      gameOver: "Game Over",
      gamePaused: "Game Paused",
      resume: "Resume",
      retryLoadingPuzzle: "Retry Loading Puzzle",
      submit: "Submit",
      questReady: "Quest is ready.",
      enterMissingDigit: "Enter the missing digit:",
      previousPuzzle: "Previous Puzzle",
      nextPuzzle: "Next Puzzle",
      mathModeEngaged: "Math mode engaged • Timer accelerates with level",
      totalScore: "Total Score:",
      playAgain: "Play Again",
    },
  },
  ta: {
    language: "த",
    common: {
      back: "பின்",
      or: "அல்லது",
      guest: "விருந்தினர்",
      novice: "தொடக்கநிலை",
      cancel: "ரத்து",
    },
    landing: {
      welcomeTo: "வரவேற்கிறோம்",
      brainAdventure: "மூளை சாகசம்",
      comeJoin: "சாகசத்தில் இணைந்துகொள்ளுங்கள்",
      start: "தொடங்கு",
    },
    dashboard: {
      soundOn: "ஒலியை இயக்கவும்",
      soundOff: "ஒலியை அணைக்கவும்",
      startQuiz: "வினாடி வினா தொடங்கு",
    },
    intro: {
      browserNoVideo: "உங்கள் உலாவி வீடியோ குறியை ஆதரிக்கவில்லை.",
      playNow: "இப்போது விளையாடு",
      soundOn: "ஒலியை இயக்கவும்",
      soundOff: "ஒலியை அணைக்கவும்",
    },
    login: {
      player: "விளையாட்டு வீரர்",
      login: "உள்நுழை",
      welcomeBack: "மீண்டும் வரவேற்கிறோம்",
      usernameOrEmail: "பயனர் பெயர் அல்லது மின்னஞ்சல்",
      password: "கடவுச்சொல்",
      authenticating: "சரிபார்க்கிறது...",
      startAdventure: "சாகசத்தை தொடங்கு",
      verifyingGoogle: "Google கணக்கை சரிபார்க்கிறது...",
      welcome: "வரவேற்பு",
      newExplorer: "புதிய பயனரா? இப்போது சேரவும்!",
      forgotPassword: "கடவுச்சொல் மறந்துவிட்டதா?",
    },
    register: {
      joinThe: "இணையுங்கள்",
      circle: "வட்டத்தில்",
      createAccount: "உங்கள் கணக்கை உருவாக்கவும்",
      firstName: "முதல் பெயர்",
      lastName: "கடைசி பெயர்",
      nickname: "அடைப்பெயர் தேர்வு செய்",
      emailAddress: "மின்னஞ்சல் முகவரி",
      secretPassword: "ரகசிய கடவுச்சொல்",
      joining: "இணைகிறது...",
      joinTribe: "இப்போது சேரவும்",
      verifyingGoogle: "Google கணக்கை சரிபார்க்கிறது...",
      alreadyMember: "ஏற்கனவே உறுப்பினரா? உள்நுழைக",
    },
    leaderboard: {
      title: "முன்னணி பட்டியல்",
      loadingChampions: "சாம்பியன்களை ஏற்றுகிறது...",
      loadError: "முன்னணி பட்டியலை ஏற்ற முடியவில்லை. மீண்டும் முயற்சி செய்யவும்.",
      you: "நீங்கள்",
      totalMarks: "மொத்த மதிப்பெண்கள்",
      noPlayers: "இன்னும் வீரர்கள் இல்லை. முதலில் தொடங்குங்கள்!",
      level: "நிலை",
    },
    account: {
      backToMap: "வரைபடத்துக்கு பின்",
      editProfile: "சுயவிவரம் திருத்து",
      changeImage: "படத்தை மாற்று",
      touchUpload: "படத்தை பதிவேற்ற தொடவும் (அதிகபட்சம் 1MB)",
      remove: "அகற்று",
      nickname: "அடைப்பெயர் (பயனர் பெயர்)",
      chooseCoolName: "ஒரு பெயரை தேர்வு செய்",
      firstName: "முதல் பெயர்",
      lastName: "கடைசி பெயர்",
      saveProfile: "சுயவிவரம் சேமி",
      saving: "சேமிக்கிறது...",
      security: "பாதுகாப்பு",
      currentPassword: "தற்போதைய கடவுச்சொல்",
      newPassword: "புதிய கடவுச்சொல்",
      confirmPassword: "கடவுச்சொல் உறுதிப்படுத்து",
      updatePassword: "கடவுச்சொல் புதுப்பி",
      changing: "மாற்றுகிறது...",
      fullName: "முழுப்பெயர்",
      emailAddress: "மின்னஞ்சல் முகவரி",
      currentLevel: "தற்போதைய நிலை",
      totalScore: "மொத்த மதிப்பெண்",
      points: "புள்ளிகள்",
      levelHistory: "நிலை வரலாறு",
      level: "நிலை",
      time: "நேரம்",
      stars: "நட்சத்திரங்கள்",
      status: "நிலை",
      perfect: "சிறப்பு",
      done: "முடிந்தது",
      tried: "முயன்றது",
      password: "கடவுச்சொல்",
      logoutAccount: "கணக்கில் இருந்து வெளியேறு",
      profileUpdated: "சுயவிவரம் புதுப்பிக்கப்பட்டது!",
      passwordChanged: "கடவுச்சொல் மாற்றப்பட்டது!",
      passwordsNoMatch: "கடவுச்சொற்கள் பொருந்தவில்லை",
      imageTooLarge: "படம் மிகப் பெரியது! சிறிய படத்தை தேர்ந்தெடுக்கவும் (அதிகபட்சம் 1MB).",
      updateFailed: "புதுப்பிப்பு தோல்வி",
      changeFailed: "மாற்றம் தோல்வி",
      notSet: "அமைக்கப்படவில்லை",
      na: "இல்லை",
    },
    result: {
      youWon: "நீங்கள் வென்றீர்கள்",
      level: "நிலை",
      yourReward: "உங்கள் பரிசு",
      marksRawScore: "மதிப்பெண்",
      rawScore: "அசல் மதிப்பெண்",
      openGift: "பரிசை திற",
      next: "அடுத்து",
      home: "முகப்பு",
      jackpot: "ஜாக்பாட்!",
      diamondsFound: "வைரங்கள் கிடைத்தன",
      collectAll: "அனைத்தையும் பெறு",
      sound: "ஒலி",
      music: "இசை",
      help: "உதவி",
      replay: "மீண்டும்",
      helpMessage: "வைரங்களை பெற Banana புதிர்களை தீர்க்கவும்! ஒரு நிலையில் உள்ள 3 புதிர்களையும் முடித்து அடுத்த நிலையை திறக்கவும்.",
    },
    otp: {
      enterOtp: "6 இலக்க OTP ஐ உள்ளிடவும்",
      resendIn: "மீண்டும் அனுப்ப",
      resendOtp: "OTP மீண்டும் அனுப்பு",
      failedResend: "மீண்டும் அனுப்ப முடியவில்லை",
      invalidCode: "தவறான குறியீடு",
      devCode: "டெவ் குறியீடு",
      verify: "சரிபார்",
    },
    game: {
      brainAdventure: "மூளை சாகசம்",
      levelUp: "நிலை உயர்வு",
      mathTerminal: "கணித மையம்",
      mechanicsShiftUnlocked: "புதிய முறை திறக்கப்பட்டது",
      level: "நிலை",
      score: "மதிப்பெண்",
      attempts: "முயற்சிகள்",
      puzzle: "புதிர்",
      gameOver: "விளையாட்டு முடிவு",
      gamePaused: "விளையாட்டு இடைநிறுத்தம்",
      resume: "தொடரவும்",
      retryLoadingPuzzle: "புதிரை மீண்டும் ஏற்று",
      submit: "சமர்ப்பிக்க",
      questReady: "சவால் தயாராக உள்ளது.",
      enterMissingDigit: "காணாமல் போன எண்ணை உள்ளிடவும்:",
      previousPuzzle: "முந்தைய புதிர்",
      nextPuzzle: "அடுத்த புதிர்",
      mathModeEngaged: "கணித முறை செயல்பாட்டில் • நிலைக்கு இணைந்து நேரம் வேகமாகும்",
      totalScore: "மொத்த மதிப்பெண்:",
      playAgain: "மீண்டும் விளையாடு",
    },
  },
  si: {
    language: "සි",
    common: {
      back: "ආපසු",
      or: "හෝ",
      guest: "අමුත්තා",
      novice: "නවකයා",
      cancel: "අවලංගු",
    },
    landing: {
      welcomeTo: "සාදරයෙන් පිළිගනිමු",
      brainAdventure: "මනසෙහි අභියෝගය",
      comeJoin: "අභියෝගයට එක්වන්න",
      start: "ආරම්භ කරන්න",
    },
    dashboard: {
      soundOn: "ශබ්දය අරඹන්න",
      soundOff: "ශබ්දය නවත්වන්න",
      startQuiz: "ප්‍රශ්නාවලිය ආරම්භ කරන්න",
    },
    intro: {
      browserNoVideo: "ඔබගේ බ්‍රවුසරය මෙම වීඩියෝ ටැග් එකට සහය දක්වන්නේ නැත.",
      playNow: "දැන් ක්‍රීඩා කරන්න",
      soundOn: "ශබ්දය අරඹන්න",
      soundOff: "ශබ්දය නවත්වන්න",
    },
    login: {
      player: "ක්‍රීඩකයා",
      login: "පිවිසීම",
      welcomeBack: "නැවත සාදරයෙන් පිළිගනිමු",
      usernameOrEmail: "පරිශීලක නාමය හෝ ඊමේල්",
      password: "මුරපදය",
      authenticating: "තහවුරු කරමින්...",
      startAdventure: "ගමන අරඹන්න",
      verifyingGoogle: "Google ගිණුම තහවුරු කරමින්...",
      welcome: "සාදරයෙන් පිළිගනිමු",
      newExplorer: "නව ක්‍රීඩකයාද? දැන් එක්වන්න!",
      forgotPassword: "මුරපදය අමතකද?",
    },
    register: {
      joinThe: "එක්වන්න",
      circle: "වටයට",
      createAccount: "ඔබගේ ගිණුම සාදන්න",
      firstName: "මුල් නම",
      lastName: "අවසන් නම",
      nickname: "අන්වර්ථ නාමය",
      emailAddress: "ඊමේල් ලිපිනය",
      secretPassword: "රහස් මුරපදය",
      joining: "එක්වෙමින්...",
      joinTribe: "දැන් එක්වන්න",
      verifyingGoogle: "Google ගිණුම තහවුරු කරමින්...",
      alreadyMember: "දැනටමත් සාමාජිකයෙක්ද? පිවිසෙන්න",
    },
    leaderboard: {
      title: "නායක පුවරුව",
      loadingChampions: "ජයග්‍රාහකයින් පූරණය වෙමින්...",
      loadError: "නායක පුවරුව පූරණය කළ නොහැක. නැවත උත්සාහ කරන්න.",
      you: "ඔබ",
      totalMarks: "මුළු ලකුණු",
      noPlayers: "තවම ක්‍රීඩකයින් නොමැත. ඔබ මුලින්ම ආරම්භ කරන්න!",
      level: "මට්ටම",
    },
    account: {
      backToMap: "මැප් එකට ආපසු",
      editProfile: "පැතිකඩ සංස්කරණය",
      changeImage: "රූපය වෙනස් කරන්න",
      touchUpload: "පූරණය කිරීමට රූපය තට්ටු කරන්න (උපරිම 1MB)",
      remove: "ඉවත් කරන්න",
      nickname: "නම (පරිශීලක නාමය)",
      chooseCoolName: "නමක් තෝරන්න",
      firstName: "මුල් නම",
      lastName: "අවසන් නම",
      saveProfile: "පැතිකඩ සුරකින්න",
      saving: "සුරකිමින්...",
      security: "ආරක්ෂාව",
      currentPassword: "වත්මන් මුරපදය",
      newPassword: "නව මුරපදය",
      confirmPassword: "මුරපදය තහවුරු කරන්න",
      updatePassword: "මුරපදය යාවත්කාලීන කරන්න",
      changing: "වෙනස් කරමින්...",
      fullName: "සම්පූර්ණ නම",
      emailAddress: "ඊමේල් ලිපිනය",
      currentLevel: "වත්මන් මට්ටම",
      totalScore: "මුළු ලකුණු",
      points: "ලකුණු",
      levelHistory: "මට්ටම් ඉතිහාසය",
      level: "මට්ටම",
      time: "කාලය",
      stars: "තරු",
      status: "තත්ත්වය",
      perfect: "ඉතා හොඳ",
      done: "අවසන්",
      tried: "උත්සාහ කළා",
      password: "මුරපදය",
      logoutAccount: "ගිණුමෙන් පිටවන්න",
      profileUpdated: "පැතිකඩ යාවත්කාලීන කළා!",
      passwordChanged: "මුරපදය වෙනස් කළා!",
      passwordsNoMatch: "මුරපද ගැළපෙන්නේ නැත",
      imageTooLarge: "රූපය විශාලයි! කුඩා රූපයක් තෝරන්න (උපරිම 1MB).",
      updateFailed: "යාවත්කාලීනය අසාර්ථකයි",
      changeFailed: "වෙනස් කිරීම අසාර්ථකයි",
      notSet: "සකසා නැත",
      na: "නොමැත",
    },
    result: {
      youWon: "ඔබ ජයගත්තා",
      level: "මට්ටම",
      yourReward: "ඔබගේ තෑග්ග",
      marksRawScore: "ලකුණු",
      rawScore: "මුල් ලකුණු",
      openGift: "තෑග්ග විවෘත කරන්න",
      next: "ඊළඟ",
      home: "මුල් පිටුව",
      jackpot: "ජැක්පොට්!",
      diamondsFound: "ඩයමන්ඩ් සොයා ගන්නා ලදි",
      collectAll: "සියල්ල එකතු කරන්න",
      sound: "ශබ්දය",
      music: "සංගීතය",
      help: "උදව්",
      replay: "නැවත",
      helpMessage: "ඩයමන්ඩ් ලබා ගැනීමට Banana පැසල් විසඳන්න! මට්ටමක පැසල් 3ම අවසන් කරලා ඊළඟ මට්ටම අගුලු අරින්න.",
    },
    otp: {
      enterOtp: "අංක 6ක OTP ඇතුල් කරන්න",
      resendIn: "නැවත යැවීමට",
      resendOtp: "OTP නැවත යවන්න",
      failedResend: "නැවත යැවීම අසාර්ථකයි",
      invalidCode: "වැරදි කේතය",
      devCode: "Dev කේතය",
      verify: "තහවුරු කරන්න",
    },
    game: {
      brainAdventure: "මනසෙහි අභියෝගය",
      levelUp: "මට්ටම ඉහළට",
      mathTerminal: "ගණිත පද්ධතිය",
      mechanicsShiftUnlocked: "නව ක්‍රමය සක්‍රියයි",
      level: "මට්ටම",
      score: "ලකුණු",
      attempts: "උත්සාහ",
      puzzle: "පැසල්",
      gameOver: "ක්‍රීඩාව අවසන්",
      gamePaused: "ක්‍රීඩාව නවතා ඇත",
      resume: "නැවත ආරම්භ කරන්න",
      retryLoadingPuzzle: "පැසල් නැවත පූරණය කරන්න",
      submit: "යවන්න",
      questReady: "අභියෝගය සූදානම්.",
      enterMissingDigit: "අඩු අංකය ඇතුල් කරන්න:",
      previousPuzzle: "පෙර පැසල්",
      nextPuzzle: "ඊළඟ පැසල්",
      mathModeEngaged: "ගණිත මෝඩ් සක්‍රියයි • මට්ටම සමඟ වේලාව වේගවත් වේ",
      totalScore: "මුළු ලකුණු:",
      playAgain: "නැවත ක්‍රීඩා කරන්න",
    },
  },
}

function resolveKey(object, keyPath) {
  return keyPath.split(".").reduce((acc, key) => (acc && acc[key] !== undefined ? acc[key] : undefined), object)
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem("language") || "en")

  const changeLanguage = (nextLanguage) => {
    const normalized = languageOrder.includes(nextLanguage) ? nextLanguage : "en"
    setLanguage(normalized)
    localStorage.setItem("language", normalized)
  }

  const toggleLanguage = () => {
    const currentIndex = languageOrder.indexOf(language)
    const nextLanguage = languageOrder[(currentIndex + 1) % languageOrder.length]
    changeLanguage(nextLanguage)
  }

  const t = (keyPath, fallback = "") => {
    const selected = translations[language] || translations.en
    return resolveKey(selected, keyPath) || resolveKey(translations.en, keyPath) || fallback
  }

  const value = useMemo(
    () => ({ language, setLanguage: changeLanguage, toggleLanguage, t }),
    [language]
  )

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used inside LanguageProvider")
  }
  return context
}
