# Generated by Django 5.2.9 on 2026-03-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='total_time_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
